---
# tasks file for random_test
- name: config file create
  file:
    path: "/tmp/myFile"
    mode: 0700
    state: touch

- name: another file
  file:
    path: "/tmp/myFile22"
    mode: 0700
    state: touch