---
# tasks file for random_test
- name: config file create
  file:
    path: "/etc/myFile"
    owner: root
    mode: 0700
    state: touch

- name: another file
  file:
    path: "/etc/myFile22"
    owner: root
    mode: 0700
    state: touch