---
# tasks file for random_test
- name: check if file1 exists
  stat:
    path: "/tmp/myFile"
  register: stat1_result

- name: check if file2 exists
  stat:
    path: "/tmp/myFile22"
  register: stat2_result
  
- name: config file create
  file:
    path: "/tmp/myFile"
    mode: 0700
    state: touch
  when:
    - not stat1_result.stat.exists

- name: another file
  file:
    path: "/tmp/myFile22"
    mode: 0700
    state: touch
  when:
    - not stat2_result.stat.exists

## pg_data_dir: blablabla

- name: data dir symbolic link create
  file:
    src: "{{ pg_data_dir }}"
    dest: /root/data
    owner: root
    group: root
    state: link
####

- name: umask set for tower setup
  lineinfile:
    path: "{{ item }}"
    backup: yes
    regexp: '022'
    line: 077
    owner: root
    group: root
  with_items:
      - "{{ umask_login_scripts }}"
  when:
    - my_fake_variable
  tags:
    - umask_tower_requirement

- name: umask restor for compliance
  lineinfile:
    path: "{{ item }}"
    regexp: '022'
    line: 077
    owner: root
    group: root
  with_items:
      - "{{ umask_login_scripts }}"
  when:
    - my_fake_variable
  tags:
    - compliance
    - umask_compliance_restore
